version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-ts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hferqb5euttd"
s3_prefix = "sam-hello-ts"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
